routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');
Route::view('contact', 'contact');
Route::view('a-propos', 'a-propos')->name('about-us');


// // Clients
// Route::get('clients', 'ClientsController@index');
// Route::get('clients/create', 'ClientsController@create');
// Route::post('clients', 'ClientsController@store');
// Route::get('clients/{client}', 'ClientsController@show');
// Route::get('clients/{client}/edit', 'ClientsController@edit');
// Route::patch('clients/{client}', 'ClientsController@update');
// Route::delete('clients/{client}', 'ClientsController@destroy');


Route::resource('clients', 'ClientsController');

//Contact

Route::get('contact', 'ContactController@create')->name('contact.create');
Route::post('contact', 'ContactController@store')->name('contact.store');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{

    protected $guarded = [];

    protected $attributes = [
        'status' => 0
    ];

    public function scopeStatus($query)
    {
        return $query->where('status', 1)->get();
    }

    public function entreprise()
    {

        return $this->belongsTo('App\Entreprise');
    }

    public function getStatusAttribute($attributes)
    {
        return $this->getStatusOptions()[$attributes];
    }

    public function getStatusOptions()
    {
        return [
            '0' => 'Inactif',
            '1' => 'Actif',
            '2' => 'En attente'
        ];
    }
}

app/Entreprise.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Entreprise extends Model
{
    protected $guarded = [];

    public function clients() {

    return $this->hasMany('App\Client');
    }


}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Client;
use App\Entreprise;

class ClientsController extends Controller
{

    public function __construct()
    {

        $this->middleware('auth')->except(['index']);
    }

    public function index()
    {
        $clients = Client::all();

        return view('clients/index', compact('clients'));
    }

    public function create()
    {
        $entreprises = Entreprise::all();
        $client = new Client();

        return view('clients/create', compact('entreprises', 'client'));
    }

    public function store()
    {

        $data = request()->validate([
            'name' => 'required|min:3',
            'email' => 'required|email',
            'status' => 'required|integer',
            'entreprise_id' => 'required|integer'

        ]);

        Client::create($data);

        return back();
    }

    public function show(Client $client)
    {

        return view('clients/show', compact('client'));
    }

    public function edit(Client $client)
    {

        $entreprises = Entreprise::all();

        return view('clients/edit', compact('client', 'entreprises'));
    }

    public function update(Client $client)
    {

        $data = request()->validate([
            'name' => 'required|min:3',
            'email' => 'required|email',
            'status' => 'required|integer',
            'entreprise_id' => 'required|integer'

        ]);

        $client->update($data);

        return redirect('clients/' . $client->id);
    }

    public function destroy(Client $client)
    {

        $client->delete();

        return redirect('clients');
    }
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use App\Mail\ContactMail;

class ContactController extends Controller
{
    public function create()
    {
        return view('contact/create');
    }

    public function store()
    {
        $data = request()->validate([
            'name' => 'required',
            'email' => 'required | email',
            'message' => 'required'
        ]);

        Mail::to('test@test.com')->send(new ContactMail($data));

        return redirect('contact')->with('message', 'Votre message a bien été envoyé');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/a-propos.blade.php
@extends ('layouts.app')

@section ('content')

<h1>About Us</h1>

@endsection

resources/views/clients/create.blade.php
@extends('layouts.app')

@section('content')
<h1>Creer un nouveau client</h1>

<form action="{{ route('clients.store') }}" method="POST">
    @include('includes/form')
    <button type="submit" class="btn btn-primary">Ajouter le client</button>

</form>

</ul>

@endsection

resources/views/clients/edit.blade.php
@extends('layouts.app')

@section('content')
<h1>Editer le profil de {{ $client->name }}</h1>

<form action="{{ route('clients.update', ['client' => $client->id]) }}" method="POST">
    @method('PATCH')
    @include('includes/form')
    <button type="submit" class="btn btn-primary">Sauvegarder les informations</button>

</form>

</ul>

@endsection

resources/views/clients/index.blade.php
@extends ('layouts.app')

@section ('content')
<h1>Clients</h1>
<a href="{{ route('clients.create') }}" class="btn btn-primary my-3">Nouveau client</a>

<ul>
    <table class="table">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Nom</th>
                <th scope="col">Status</th>
                <th scope="col">Entreprise</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($clients as $client)
            <tr>
                <th scope="row">{{ $client->id }}</th>
                <td><a href="/clients/{{ $client->id }}">{{ $client->name }}</a></td>
                <td>{{ $client->status }}</td>
                <td>{{ $client->entreprise->name }}</td>
            </tr>
        </tbody>
        @endforeach

    </table>

    @endsection

resources/views/clients/show.blade.php
@extends ('layouts.app')

@section('content')

<h1>{{ $client->name }}</h1>
<a href="{{ route('clients.edit', ['client' => $client->id]) }}" class="btn btn-secondary my-3">Editer</a>
<form action="{{ route('clients.destroy', ['client' => $client->id]) }}" method="POST" style="display: inline;">
    @csrf
    @method('DELETE')
    <button type="submit" class="btn btn-danger">Supprimer</button>
<hr>
<p><strong>Email :</strong> {{ $client->email }}</p>
<p><strong>Entreprise :</strong> {{ $client->entreprise->name }}</p>






@endsection

resources/views/contact/create.blade.php
@extends ('layouts.app')

@section ('content')

<h1>Contactez-nous</h1>

@if (!session()->has('message'))

<form action="{{ route('contact.store') }}" method="POST">
    @csrf

    <div class="form-group">
        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name"
            placeholder="Votre nom..." value="{{ old('name')}}">
        @error('name')
        <div class="invalid-feedback">
            {{ $errors->first('name') }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        <input type="email" class="form-control @error('email') is-invalid @enderror" name="email"
            placeholder="Votre email..." value="{{ old('email')}}">
        @error('email')
        <div class="invalid-feedback">
            {{ $errors->first('email') }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        <textarea name="message" cols="30" rows="10" class="form-control" @error('mesage') is-invalid @enderror
            placeholder="Votre message...">{{ old('message') }}</textarea>
        @error('message')
        <div class="invalid-feedback">
            {{ $errors->first('message') }}
        </div>
        @enderror
    </div>

    <button type="submit" class="btn btn-primary">Envoyer mon message</button>

</form>

@endif

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/includes/form.blade.php
@csrf
<div class="form-group">
    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name"
        placeholder="Entrez un pseudo..." value="{{ old('name') ?? $client->name }}">
    @error('name')
    <div class="invalid-feedback">
        {{ $errors->first('name') }}
    </div>
    @enderror
</div>

<div class="form-group">
    <input type="email" class="form-control @error('email') is-invalid @enderror" name="email"
        placeholder="Entrez un email..." value="{{ old('email') ?? $client->email }}">
    @error('email')
    <div class="invalid-feedback">
        {{ $errors->first('email') }}
    </div>
    @enderror
</div>

<div class="form-group">
    <select class="custom-select @error('status') is-invalid @enderror" name="status">
        @foreach ($client->getStatusOptions() as $key => $value )
        <option value="{{ $key }}" {{ $client->status == $value ? 'selected' : '' }}>{{ $value }}</option>
        @endforeach
    </select>
    @error('status')
    <div class="invalid-feedback">
        {{ $errors->first('status') }}
    </div>
    @enderror
</div>

<div class="form-group">
    <select class="custom-select @error('entreprise_id') is-invalid @enderror" name="entreprise_id">
        @foreach ($entreprises as $entreprise )
        <option value="{{ $entreprise->id }}" {{ $client->entreprise_id == $entreprise->id ? 'selected' : ' '  }}>
            {{ $entreprise->name }}</option>
        @endforeach
    </select>
    @error('entreprise_id')
    <div class="invalid-feedback">
        {{ $errors->first('entreprise_id') }}
    </div>
    @enderror
</div>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="/">Accueil</a>
                        </li>
                        <li class="nav-item">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ action('HomeController@index') }}">Panel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('about-us') }}">A propos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('contact.store') }}">Contactez-nous</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('clients.index') }}">Voir nos clients</a>
                        </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Se connecter') }}</a>
                        </li>
                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('S\'enregister') }}</a>
                        </li>
                        @endif
                        @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Se déconnecter') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                    style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4 container">
            @if (session()->has('message'))
            <div class="alert alert-success" role="alert">
                {{ session()->get('message') }}
            </div>
            @endif
            @yield('content')
        </main>
    </div>
</body>

</html>